name: Pre-commit auto-fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

  auto-fix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run pre-commit with auto-fixes
        id: precommit
        continue-on-error: true
        run: |
          uv run pre-commit run --all-files || echo "CHANGES_MADE=true" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.CHANGES_MADE == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: auto-fixes from pre-commit"
          title: "style: auto-fixes from pre-commit"
          body: |
            This PR contains automated fixes from pre-commit hooks.

            The following hooks were run:
            - trailing-whitespace
            - end-of-file-fixer
            - check-yaml
            - check-added-large-files
            - black
            - ruff
            - mypy
            - pyupgrade
          branch: pre-commit-fixes
          branch-suffix: timestamp
          delete-branch: true
